services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/horoscope_db
      - JWT_SECRET=supersecret_change_me
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_MAX=5
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo-data:
